<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="5" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-01T16:59:14 IST" name="Suite" finished-at="2025-05-01T16:59:23 IST" duration-ms="8326">
    <groups>
    </groups>
    <test started-at="2025-05-01T16:59:14 IST" name="Test" finished-at="2025-05-01T16:59:23 IST" duration-ms="8326">
      <class name="tests.ListOfUsers">
        <test-method signature="verifyGetAllUsers()[pri:0, instance:tests.ListOfUsers@7068e664]" started-at="2025-05-01T16:59:22 IST" name="verifyGetAllUsers" finished-at="2025-05-01T16:59:23 IST" duration-ms="123" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyGetAllUsers -->
      </class> <!-- tests.ListOfUsers -->
      <class name="tests.UpdateTest">
        <test-method signature="verifyUpdatePatch()[pri:0, instance:tests.UpdateTest@4ee203eb]" started-at="2025-05-01T16:59:19 IST" name="verifyUpdatePatch" finished-at="2025-05-01T16:59:21 IST" duration-ms="1540" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUpdatePatch -->
        <test-method signature="verifyUpdatePut()[pri:0, instance:tests.UpdateTest@4ee203eb]" started-at="2025-05-01T16:59:21 IST" name="verifyUpdatePut" finished-at="2025-05-01T16:59:22 IST" duration-ms="532" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[failed status code for put request. expected [201] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: failed status code for put request. expected [201] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at tests.UpdateTest.verifyUpdatePut(UpdateTest.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUpdatePut -->
      </class> <!-- tests.UpdateTest -->
      <class name="tests.UserTests">
        <test-method signature="verifyCreateUser()[pri:0, instance:tests.UserTests@1a5a4e19]" started-at="2025-05-01T16:59:22 IST" name="verifyCreateUser" finished-at="2025-05-01T16:59:22 IST" duration-ms="521" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCreateUser -->
        <test-method signature="verifyUserNotFound()[pri:0, instance:tests.UserTests@1a5a4e19]" started-at="2025-05-01T16:59:22 IST" name="verifyUserNotFound" finished-at="2025-05-01T16:59:22 IST" duration-ms="102" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Status code failed. expected [403] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Status code failed. expected [403] but found [404]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1431)
at org.testng.Assert.assertEquals(Assert.java:1395)
at tests.UserTests.verifyUserNotFound(UserTests.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserNotFound -->
        <test-method signature="verifygetUser()[pri:0, instance:tests.UserTests@1a5a4e19]" started-at="2025-05-01T16:59:22 IST" name="verifygetUser" finished-at="2025-05-01T16:59:22 IST" duration-ms="115" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifygetUser -->
      </class> <!-- tests.UserTests -->
      <class name="tests.DeleteUserTest">
        <test-method signature="verifyDeleteUser()[pri:0, instance:tests.DeleteUserTest@3b6d844d]" started-at="2025-05-01T16:59:14 IST" name="verifyDeleteUser" finished-at="2025-05-01T16:59:19 IST" duration-ms="5185" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDeleteUser -->
      </class> <!-- tests.DeleteUserTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
